title: doutrina.org
description: plataforma de estudos

remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

show_downloads: false

# Build settings
markdown: kramdown
  